linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosec
    - revive

linters-settings:
  revive:
    rules:
      - name: exported
        arguments:
          - disable-stuttering-check
