# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    main: ./cmd/opspulse
    ldflags:
      - -s -w
      - -X github.com/volcano6/opspulse/internal/version.Version={{.Version}}
      - -X github.com/volcano6/opspulse/internal/version.Commit={{.Commit}}
      - -X github.com/volcano6/opspulse/internal/version.Date={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
