package server

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/volcano6/opspulse/internal/secret"
)

const (
	// MarkerBegin marks the start of Ops-managed configuration in ~/.ssh/config.
	MarkerBegin = "# >>> BEGIN OpsPulse Managed Hosts >>>"
	// MarkerEnd marks the end of Ops-managed configuration in ~/.ssh/config.
	MarkerEnd = "# <<< END OpsPulse Managed Hosts <<<"
)

// DefaultSSHConfigPath returns the canonical path to ~/.ssh/config.
func DefaultSSHConfigPath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("determine user home directory: %w", err)
	}
	return filepath.Join(home, ".ssh", "config"), nil
}

// RenderSSHConfig renders the OpenSSH config block for the provided servers.
func RenderSSHConfig(servers []Server) string {
	var buf bytes.Buffer
	buf.WriteString(MarkerBegin + "\n")
	buf.WriteString("# Do not edit this section directly. Automatically generated by Ops (ops export ssh-config).\n\n")

	if len(servers) == 0 {
		buf.WriteString("# No managed hosts configured in Ops inventory.\n")
		buf.WriteString(MarkerEnd + "\n")
		return buf.String()
	}

	// Sort servers alphabetically by name for deterministic output
	sorted := make([]Server, len(servers))
	copy(sorted, servers)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].Name < sorted[j].Name
	})

	for i, s := range sorted {
		if i > 0 {
			buf.WriteString("\n")
		}

		var descParts []string
		if s.Description != "" {
			descParts = append(descParts, s.Description)
		}
		if len(s.Tags) > 0 {
			descParts = append(descParts, fmt.Sprintf("tags: %s", strings.Join(s.Tags, ",")))
		}
		if len(s.Labels) > 0 && s.FormatLabels() != "-" {
			descParts = append(descParts, fmt.Sprintf("labels: %s", s.FormatLabels()))
		}
		if len(descParts) > 0 {
			buf.WriteString(fmt.Sprintf("# %s\n", strings.Join(descParts, " | ")))
		}

		user := s.User
		if user == "" {
			user = "root"
		}
		port := s.Port
		if port <= 0 {
			port = 22
		}

		buf.WriteString(fmt.Sprintf("Host %s\n", s.Name))
		buf.WriteString(fmt.Sprintf("    HostName %s\n", s.Host))
		buf.WriteString(fmt.Sprintf("    User %s\n", user))
		if port != 22 {
			buf.WriteString(fmt.Sprintf("    Port %d\n", port))
		}

		switch {
		case secret.Is1PRef(s.KeyPath):
			// ssh(1) cannot read op:// references, so exporting one as
			// IdentityFile would produce a config that silently fails to
			// authenticate. Leave a pointer instead of something broken.
			buf.WriteString(fmt.Sprintf("# private key is held in 1Password: %s\n", s.KeyPath))
			buf.WriteString(fmt.Sprintf("# use 'ops ssh %s', or run 'ops 1p pull %s' to materialise it locally\n", s.Name, s.Name))
		case s.KeyPath != "":
			buf.WriteString(fmt.Sprintf("    IdentityFile %s\n", s.KeyPath))
			buf.WriteString("    IdentitiesOnly yes\n")
		case s.Password != "":
			buf.WriteString("    PubkeyAuthentication no\n")
			buf.WriteString("    PreferredAuthentications password,keyboard-interactive\n")
		}

		buf.WriteString("    HostKeyAlgorithms +ssh-rsa,ssh-dss\n")
		buf.WriteString("    PubkeyAcceptedKeyTypes +ssh-rsa\n")

		if s.JumpHost != "" {
			buf.WriteString(fmt.Sprintf("    ProxyJump %s\n", s.JumpHost))
		}
	}

	buf.WriteString(MarkerEnd + "\n")
	return buf.String()
}

// UpdateSSHConfigFile idempotently inserts or updates the OpsPulse managed block in the given SSH config file.
// If filePath is empty, the default path ~/.ssh/config is used.
func UpdateSSHConfigFile(filePath string, servers []Server) (string, int, error) {
	if filePath == "" {
		var err error
		filePath, err = DefaultSSHConfigPath()
		if err != nil {
			return "", 0, err
		}
	}

	block := RenderSSHConfig(servers)

	dir := filepath.Dir(filePath)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return "", 0, fmt.Errorf("create ssh directory %s: %w", dir, err)
	}

	var existingContent string
	if data, readErr := os.ReadFile(filepath.Clean(filePath)); readErr == nil {
		existingContent = string(data)
	} else if !os.IsNotExist(readErr) {
		return "", 0, fmt.Errorf("read existing ssh config %s: %w", filePath, readErr)
	}

	newContent := MergeSSHConfigContent(existingContent, block)

	// Write atomically via temporary file in the same directory
	tempFile, err := os.CreateTemp(dir, "ssh_config.*.tmp")
	if err != nil {
		return "", 0, fmt.Errorf("create temp ssh config file: %w", err)
	}
	tempPath := tempFile.Name()
	defer func() {
		_ = tempFile.Close()
		_ = os.Remove(tempPath)
	}()

	if _, err := tempFile.WriteString(newContent); err != nil {
		return "", 0, fmt.Errorf("write temp ssh config: %w", err)
	}
	if err := tempFile.Close(); err != nil {
		return "", 0, fmt.Errorf("close temp ssh config: %w", err)
	}

	_ = os.Chmod(tempPath, 0o600)

	if err := os.Rename(tempPath, filePath); err != nil {
		// Fallback for Windows file rename when destination file exists
		backupPath := fmt.Sprintf("%s.bak.%d", filePath, time.Now().UnixNano())
		if renameBackupErr := os.Rename(filePath, backupPath); renameBackupErr == nil {
			if retryErr := os.Rename(tempPath, filePath); retryErr != nil {
				_ = os.Rename(backupPath, filePath) // restore original on failure
				return "", 0, fmt.Errorf("replace ssh config %s: %w", filePath, retryErr)
			}
			_ = os.Remove(backupPath)
		} else {
			_ = os.Remove(filePath)
			if retryErr := os.Rename(tempPath, filePath); retryErr != nil {
				return "", 0, fmt.Errorf("replace ssh config %s: %w", filePath, retryErr)
			}
		}
	}
	_ = os.Chmod(filePath, 0o600)

	return newContent, len(servers), nil
}

// MergeSSHConfigContent replaces the managed block if present, or appends it cleanly.
func MergeSSHConfigContent(existing, block string) string {
	normExisting := strings.ReplaceAll(existing, "\r\n", "\n")
	normBlock := strings.ReplaceAll(block, "\r\n", "\n")

	beginIdx := strings.Index(normExisting, MarkerBegin)
	endIdx := strings.Index(normExisting, MarkerEnd)

	if beginIdx != -1 && endIdx != -1 && endIdx >= beginIdx {
		postEnd := endIdx + len(MarkerEnd)
		if postEnd < len(normExisting) && normExisting[postEnd] == '\n' {
			postEnd++
		}

		prefix := normExisting[:beginIdx]
		suffix := normExisting[postEnd:]
		return prefix + normBlock + suffix
	}

	trimmed := strings.TrimRight(normExisting, "\n")
	if trimmed == "" {
		return normBlock
	}
	return trimmed + "\n\n" + normBlock
}
